import React, { useState, useEffect } from 'react';
import {
  Calendar as CalendarIcon,
  Clock,
  AlertTriangle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Plus,
  Trash2,
  Download,
  Share2,
  ExternalLink,
  Milestone,
  Scale,
  Sparkles,
  Gavel,
  ShieldAlert,
  FileText,
  CalendarDays,
  Filter,
  Check,
  Copy,
  Info
} from 'lucide-react';

export interface TimelineEvent {
  id: string;
  title: string;
  category: 'DEADLINE' | 'HEARING' | 'STATUTE' | 'PROCEDURAL';
  date: string; // YYYY-MM-DD
  time?: string; // HH:mm
  lawReference?: string;
  consequence?: string;
  court?: string;
  caseNo?: string;
  notes?: string;
  status: 'URGENT' | 'UPCOMING' | 'COMPLETED' | 'EXPIRED';
  autoGenerated?: boolean;
}

interface CaseTimelineProps {
  caseSummary?: string;
  eventDate?: string;
  clientClaims?: string;
  courtName?: string;
  caseNumber?: string;
  onApplyToPetition?: (text: string) => void;
}

export function CaseTimeline({
  caseSummary,
  eventDate,
  clientClaims,
  courtName,
  caseNumber,
  onApplyToPetition
}: CaseTimelineProps) {
  // Calendar View State: 'calendar' | 'timeline' | 'urgent_table'
  const [activeView, setActiveView] = useState<'calendar' | 'timeline' | 'urgent_table'>('calendar');
  const [currentDate, setCurrentDate] = useState<Date>(new Date(2026, 8, 24)); // September 2026
  const [selectedDateStr, setSelectedDateStr] = useState<string>('2026-09-28');
  const [categoryFilter, setCategoryFilter] = useState<'ALL' | 'DEADLINE' | 'HEARING' | 'STATUTE' | 'PROCEDURAL'>('ALL');
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Form State for Adding New Event
  const [showAddModal, setShowAddModal] = useState<boolean>(false);
  const [newTitle, setNewTitle] = useState<string>('');
  const [newCategory, setNewCategory] = useState<TimelineEvent['category']>('DEADLINE');
  const [newDate, setNewDate] = useState<string>('2026-10-05');
  const [newTime, setNewTime] = useState<string>('10:00');
  const [newLawRef, setNewLawRef] = useState<string>('HMK m. 281');
  const [newConsequence, setNewConsequence] = useState<string>('Süresinde itiraz edilmezse rapor kesinleşir.');
  const [newCourt, setNewCourt] = useState<string>(courtName || 'İstanbul 14. Asliye Ticaret Mahkemesi');
  const [newCaseNo, setNewCaseNo] = useState<string>(caseNumber || '2026/412 E.');
  const [newNotes, setNewNotes] = useState<string>('');

  // Preset Procedural Calculator
  const [calcNoticeDate, setCalcNoticeDate] = useState<string>('2026-09-24');
  const [calcRuleType, setCalcRuleType] = useState<string>('hmk_281');

  // Events State with localStorage persistence
  const [events, setEvents] = useState<TimelineEvent[]>(() => {
    try {
      const saved = localStorage.getItem('ultra_hukuk_case_timeline_events');
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed)) return parsed;
      }
    } catch (e) {
      console.warn('Failed to load timeline events:', e);
    }
    return [];
  });

  // Save to localStorage
  useEffect(() => {
    try {
      localStorage.setItem('ultra_hukuk_case_timeline_events', JSON.stringify(events));
    } catch (e) {
      console.warn('Failed to save timeline events:', e);
    }
  }, [events]);

  // Procedural calculator helper (HMK rules: 2 weeks, 1 week, 1 month, 10 years, adli tatil)
  const calculateProceduralDeadline = (noticeDateStr: string, rule: string) => {
    const baseDate = new Date(noticeDateStr);
    if (isNaN(baseDate.getTime())) return new Date();

    const result = new Date(baseDate);

    switch (rule) {
      case 'hmk_281': // Bilirkişi raporuna itiraz: 2 Hafta
      case 'hmk_122': // Cevap dilekçesi verme süresi: 2 Hafta
      case 'hmk_345': // İstinaf başvuru süresi: 2 Hafta
      case 'hmk_361': // Temyiz başvuru süresi: 2 Hafta
        result.setDate(result.getDate() + 14);
        break;
      case 'hmk_394': // İhtiyati tedbire itiraz: 1 Hafta
        result.setDate(result.getDate() + 7);
        break;
      case 'is_kanunu': // İşe iade dava açma: 1 Ay
        result.setMonth(result.getMonth() + 1);
        break;
      case 'tbk_72_2': // Haksız fiil 2 yıl
        result.setFullYear(result.getFullYear() + 2);
        break;
      case 'tbk_146': // Genel zamanaşımı 10 yıl
        result.setFullYear(result.getFullYear() + 10);
        break;
      case 'tbk_147': // Kira 5 yıl
        result.setFullYear(result.getFullYear() + 5);
        break;
      default:
        result.setDate(result.getDate() + 14);
    }

    // HMK m. 93 Weekend rule: If falls on Saturday or Sunday, moves to next Monday
    const dayOfWeek = result.getDay();
    if (dayOfWeek === 6) {
      // Saturday -> Monday (+2 days)
      result.setDate(result.getDate() + 2);
    } else if (dayOfWeek === 0) {
      // Sunday -> Monday (+1 day)
      result.setDate(result.getDate() + 1);
    }

    // HMK m. 104 Adli Tatil rule: If deadline falls between 20 July - 31 August, extends 1 week from Sept 1 (Sept 7)
    const month = result.getMonth(); // 0-indexed: 6 = July, 7 = August, 8 = Sept
    const date = result.getDate();
    const isAdliTatil = (month === 6 && date >= 20) || month === 7;
    if (isAdliTatil) {
      result.setMonth(8); // September
      result.setDate(7); // 7th September
    }

    return result;
  };

  const handleApplyProceduralCalculation = () => {
    const calcDate = calculateProceduralDeadline(calcNoticeDate, calcRuleType);
    const dateStr = calcDate.toISOString().split('T')[0];
    setNewDate(dateStr);

    let titleStr = 'Bilirkişi Raporuna İtiraz Süresi';
    let lawRefStr = 'HMK m. 281';
    let consequenceStr = 'Hak düşürücü süredir; süresinde itiraz edilmezse rapor kesinleşir.';

    if (calcRuleType === 'hmk_122') {
      titleStr = 'Cevap Dilekçesi Verme Kesin Süresi';
      lawRefStr = 'HMK m. 122';
      consequenceStr = 'İlk itirazlar düşer, savunmanın genişletilmesi yasağı başlar.';
    } else if (calcRuleType === 'hmk_345') {
      titleStr = 'BAM İstinaf Kanun Yolu Başvurusu';
      lawRefStr = 'HMK m. 345';
      consequenceStr = 'Karar kesinleşir; istinaf hakkı ortadan kalkar.';
    } else if (calcRuleType === 'hmk_394') {
      titleStr = 'İhtiyati Tedbir Kararına İtiraz';
      lawRefStr = 'HMK m. 394';
      consequenceStr = 'Tedbir tedbiren uygulanmaya devam eder; itiraz hakkı düşer.';
    } else if (calcRuleType === 'tbk_72_2') {
      titleStr = 'Haksız Fiil 2 Yıllık Zamanaşımı';
      lawRefStr = 'TBK m. 72';
      consequenceStr = 'Zamanaşımı def\'i halinde tazminat istemi reddedilir.';
    } else if (calcRuleType === 'tbk_146') {
      titleStr = 'TBK 10 Yıllık Genel Zamanaşımı';
      lawRefRef(calcRuleType);
      consequenceStr = 'Alacak zamanaşımına uğrar; borç eksik borca dönüşür.';
    }

    setNewTitle(titleStr);
    setNewLawRef(lawRefStr);
    setNewConsequence(consequenceStr);
  };

  function lawRefRef(rule: string) {
    if (rule === 'tbk_146') setNewLawRef('TBK m. 146');
  }

  // Days remaining calculation
  const getDaysRemaining = (targetDateStr: string) => {
    const today = new Date(2026, 8, 24); // Sept 24, 2026
    today.setHours(0, 0, 0, 0);
    const target = new Date(targetDateStr);
    target.setHours(0, 0, 0, 0);

    const diffMs = target.getTime() - today.getTime();
    return Math.ceil(diffMs / (1000 * 60 * 60 * 24));
  };

  const getUrgencyBadge = (targetDateStr: string, status: TimelineEvent['status']) => {
    if (status === 'COMPLETED') {
      return (
        <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400 border border-emerald-300 dark:border-emerald-800 flex items-center gap-1">
          <CheckCircle2 className="w-3 h-3" /> Tamamlandı
        </span>
      );
    }

    const days = getDaysRemaining(targetDateStr);

    if (days < 0) {
      return (
        <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-rose-100 dark:bg-rose-950/40 text-rose-700 dark:text-rose-400 border border-rose-300 dark:border-rose-800 flex items-center gap-1">
          <AlertTriangle className="w-3 h-3" /> Süresi Doldu ({Math.abs(days)} gün önce)
        </span>
      );
    } else if (days === 0) {
      return (
        <span className="text-[10px] font-extrabold px-2.5 py-0.5 rounded-full bg-rose-600 text-white animate-pulse flex items-center gap-1 shadow-xs">
          <AlertTriangle className="w-3 h-3" /> BUGÜN SON GÜN!
        </span>
      );
    } else if (days <= 4) {
      return (
        <span className="text-[10px] font-extrabold px-2.5 py-0.5 rounded-full bg-amber-500 text-white flex items-center gap-1 shadow-xs">
          <Clock className="w-3 h-3" /> ⚠️ {days} Gün Kaldı (Acil!)
        </span>
      );
    } else if (days <= 14) {
      return (
        <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-amber-100 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border border-amber-300 dark:border-amber-800 flex items-center gap-1">
          <Clock className="w-3 h-3" /> {days} Gün Kaldı
        </span>
      );
    } else {
      return (
        <span className="text-[10px] font-medium px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 flex items-center gap-1">
          <Clock className="w-3 h-3" /> {days} Gün Kaldı
        </span>
      );
    }
  };

  const getCategoryBadge = (category: TimelineEvent['category']) => {
    switch (category) {
      case 'DEADLINE':
        return {
          label: 'Kesin / Hak Düşürücü Süre',
          color: 'bg-rose-100 dark:bg-rose-900/40 text-rose-700 dark:text-rose-300 border-rose-300 dark:border-rose-800'
        };
      case 'HEARING':
        return {
          label: 'Duruşma / Celse',
          color: 'bg-sky-100 dark:bg-sky-900/40 text-sky-700 dark:text-sky-300 border-sky-300 dark:border-sky-800'
        };
      case 'STATUTE':
        return {
          label: 'Zamanaşımı Dolumu',
          color: 'bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300 border-purple-300 dark:border-purple-800'
        };
      case 'PROCEDURAL':
        return {
          label: 'Usul & Arabuluculuk',
          color: 'bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-300 border-amber-300 dark:border-amber-800'
        };
    }
  };

  // Add event handler
  const handleAddEvent = () => {
    if (!newTitle.trim() || !newDate) return;

    const days = getDaysRemaining(newDate);
    const calculatedStatus: TimelineEvent['status'] =
      days < 0 ? 'EXPIRED' : days <= 4 ? 'URGENT' : 'UPCOMING';

    const item: TimelineEvent = {
      id: `evt-${Date.now()}`,
      title: newTitle.trim(),
      category: newCategory,
      date: newDate,
      time: newTime || '10:00',
      lawReference: newLawRef,
      consequence: newConsequence,
      court: newCourt,
      caseNo: newCaseNo,
      notes: newNotes,
      status: calculatedStatus,
      autoGenerated: false
    };

    setEvents((prev) => [...prev, item].sort((a, b) => a.date.localeCompare(b.date)));
    setShowAddModal(false);
    setNewTitle('');
    setNewNotes('');
  };

  const handleDeleteEvent = (id: string) => {
    setEvents((prev) => prev.filter((e) => e.id !== id));
  };

  const handleToggleCompleted = (id: string) => {
    setEvents((prev) =>
      prev.map((e) => {
        if (e.id === id) {
          const nextStatus = e.status === 'COMPLETED' ? 'UPCOMING' : 'COMPLETED';
          return { ...e, status: nextStatus };
        }
        return e;
      })
    );
  };

  // Google Calendar Link Generator
  const generateGoogleCalendarUrl = (evt: TimelineEvent) => {
    const cleanDate = evt.date.replace(/-/g, '');
    const cleanTime = (evt.time || '10:00').replace(/:/g, '') + '00';
    const startStr = `${cleanDate}T${cleanTime}`;

    // Add 1 hour for end time
    const endHour = (parseInt((evt.time || '10').split(':')[0]) + 1).toString().padStart(2, '0');
    const endStr = `${cleanDate}T${endHour}0000`;

    const titleEncoded = encodeURIComponent(`[UYAP DAVA SÜRESİ] ${evt.title} - ${evt.court || ''}`);
    const detailsEncoded = encodeURIComponent(
      `DOSYA NO: ${evt.caseNo || ''}\nMAHKEME: ${evt.court || ''}\nHUKUKİ DAYANAK: ${evt.lawReference || ''}\nKAÇIRILIRSA SONUÇ: ${
        evt.consequence || ''
      }\nNOTLAR: ${evt.notes || ''}\n\n*Ultra Hukuk AI Dava Takvimi tarafından oluşturulmuştur.`
    );
    const locationEncoded = encodeURIComponent(evt.court || 'Adliye Mahkemesi');

    return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${titleEncoded}&dates=${startStr}/${endStr}&details=${detailsEncoded}&location=${locationEncoded}`;
  };

  // iCal (.ics) Downloader
  const downloadIcsFile = (evt?: TimelineEvent) => {
    const targetEvents = evt ? [evt] : events;
    let icsContent = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Ultra Hukuk AI//Dava Sure Takvimi//TR',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH'
    ].join('\r\n');

    targetEvents.forEach((e) => {
      const d = e.date.replace(/-/g, '');
      const t = (e.time || '10:00').replace(/:/g, '') + '00';
      const dtStart = `${d}T${t}`;
      const endHour = (parseInt((e.time || '10').split(':')[0]) + 1).toString().padStart(2, '0');
      const dtEnd = `${d}T${endHour}0000`;

      icsContent += '\r\n' + [
        'BEGIN:VEVENT',
        `UID:${e.id}@ultrahukuk.ai`,
        `DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z`,
        `DTSTART:${dtStart}`,
        `DTEND:${dtEnd}`,
        `SUMMARY:[UYAP] ${e.title} (${e.lawReference || ''})`,
        `DESCRIPTION:${e.consequence || ''} - Dosya: ${e.caseNo || ''}`,
        `LOCATION:${e.court || 'Adliye'}`,
        'STATUS:CONFIRMED',
        'BEGIN:VALARM',
        'TRIGGER:-P1D',
        'ACTION:DISPLAY',
        `DESCRIPTION:Hatırlatma: ${e.title} yarın son gün!`,
        'END:VALARM',
        'END:VEVENT'
      ].join('\r\n');
    });

    icsContent += '\r\nEND:VCALENDAR';

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', evt ? `dava-sure-${evt.date}.ics` : 'tum-dava-sureleri.ics');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Copy timeline summary to clipboard
  const handleCopyTimelineSummary = () => {
    const text = events
      .map(
        (e, idx) =>
          `${idx + 1}. [${e.date} ${e.time || ''}] ${e.title} (${e.lawReference || ''})\n   Mahkeme/Dosya: ${
            e.court || ''
          } - ${e.caseNo || ''}\n   Hukuki Sonuç: ${e.consequence || ''}\n   Durum: ${
            e.status === 'COMPLETED' ? 'Tamamlandı' : `${getDaysRemaining(e.date)} gün kaldı`
          }`
      )
      .join('\n\n');

    navigator.clipboard.writeText(text);
    setCopiedId('all');
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Calendar Math (Month Matrix)
  const year = currentDate.getFullYear();
  const month = currentDate.getMonth(); // 0-indexed

  const monthNames = [
    'Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
    'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'
  ];

  const firstDayOfMonth = new Date(year, month, 1);
  const lastDayOfMonth = new Date(year, month + 1, 0);

  // In Turkey/ISO, Monday is 0, Sunday is 6
  let firstDayIndex = firstDayOfMonth.getDay() - 1;
  if (firstDayIndex === -1) firstDayIndex = 6;

  const totalDays = lastDayOfMonth.getDate();

  const prevMonth = () => {
    setCurrentDate(new Date(year, month - 1, 1));
  };

  const nextMonth = () => {
    setCurrentDate(new Date(year, month + 1, 1));
  };

  const jumpToToday = () => {
    setCurrentDate(new Date(2026, 8, 24)); // Sept 24, 2026
    setSelectedDateStr('2026-09-24');
  };

  // Filtered events
  const filteredEvents = events.filter((e) => {
    if (categoryFilter === 'ALL') return true;
    return e.category === categoryFilter;
  });

  // Events on selected calendar date
  const selectedDateEvents = events.filter((e) => e.date === selectedDateStr);

  return (
    <div className="space-y-6">
      {/* Top Banner & Quick Metrics */}
      <div className="bg-white dark:bg-[#131d31] border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-800 pb-4">
          <div>
            <div className="flex items-center gap-2 mb-1 flex-wrap">
              <span className="p-1.5 rounded-lg bg-sky-500/10 text-sky-600 dark:text-sky-400 border border-sky-500/20">
                <CalendarDays className="w-4 h-4" />
              </span>
              <h2 className="text-base font-bold text-slate-900 dark:text-slate-100">
                Dava Zaman Çizelgesi & Dinamik Adli Takvim (Case Timeline)
              </h2>
              <span className="text-[11px] font-semibold px-2.5 py-0.5 rounded-full bg-rose-100 dark:bg-rose-950/40 text-rose-700 dark:text-rose-400 border border-rose-300 dark:border-rose-800">
                HMK m. 90-94 & Adli Tatil Algoritması
              </span>
            </div>
            <p className="text-xs text-slate-600 dark:text-slate-400">
              Kritik mahkeme sürelerini, duruşma tarihlerini ve zamanaşımı eşiklerini dinamik takvimle takip edin; Google
              Calendar ve Apple/Outlook (.ics) ile anlık senkronize edin.
            </p>
          </div>

          {/* Action Toolbar */}
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={() => setShowAddModal(true)}
              className="flex items-center gap-1.5 px-3.5 py-2 bg-sky-600 hover:bg-sky-500 text-white rounded-xl text-xs font-bold transition shadow-sm"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Yeni Süre / Duruşma Ekle</span>
            </button>

            <button
              onClick={() => downloadIcsFile()}
              className="flex items-center gap-1.5 px-3 py-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-semibold border border-slate-200 dark:border-slate-700 transition"
              title="Tüm Süreleri iCalendar (.ics) formatında indir"
            >
              <Download className="w-3.5 h-3.5" />
              <span>.ICS İndir</span>
            </button>

            <button
              onClick={handleCopyTimelineSummary}
              className="flex items-center gap-1.5 px-3 py-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-semibold border border-slate-200 dark:border-slate-700 transition"
              title="Tüm Zaman Çizelgesini Metin Olarak Kopyala"
            >
              {copiedId === 'all' ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-500" />
                  <span className="text-emerald-600 font-bold">Kopyalandı</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Özeti Kopyala</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Status Dashboard Mini Cards */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-1">
          <div className="bg-rose-50/60 dark:bg-rose-950/20 border border-rose-200 dark:border-rose-900/40 rounded-xl p-3">
            <span className="text-[10px] font-bold uppercase tracking-wider text-rose-600 dark:text-rose-400 block">
              Yaklaşan Kesin Süreler
            </span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-xl font-black text-rose-700 dark:text-rose-300">
                {events.filter((e) => e.category === 'DEADLINE' && e.status !== 'COMPLETED').length}
              </span>
              <span className="text-[11px] text-rose-600 font-semibold">HMK Hak Düşürücü</span>
            </div>
          </div>

          <div className="bg-sky-50/60 dark:bg-sky-950/20 border border-sky-200 dark:border-sky-900/40 rounded-xl p-3">
            <span className="text-[10px] font-bold uppercase tracking-wider text-sky-600 dark:text-sky-400 block">
              Duruşma ve Celseler
            </span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-xl font-black text-sky-700 dark:text-sky-300">
                {events.filter((e) => e.category === 'HEARING').length}
              </span>
              <span className="text-[11px] text-sky-600 font-semibold">Celse / Keşif</span>
            </div>
          </div>

          <div className="bg-purple-50/60 dark:bg-purple-950/20 border border-purple-200 dark:border-purple-900/40 rounded-xl p-3">
            <span className="text-[10px] font-bold uppercase tracking-wider text-purple-600 dark:text-purple-400 block">
              Zamanaşımı Eşikleri
            </span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-xl font-black text-purple-700 dark:text-purple-300">
                {events.filter((e) => e.category === 'STATUTE').length}
              </span>
              <span className="text-[11px] text-purple-600 font-semibold">TBK & TMK Sınırı</span>
            </div>
          </div>

          <div className="bg-emerald-50/60 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-900/40 rounded-xl p-3">
            <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-400 block">
              İcra Edilen Süreler
            </span>
            <div className="flex items-baseline gap-2 mt-1">
              <span className="text-xl font-black text-emerald-700 dark:text-emerald-300">
                {events.filter((e) => e.status === 'COMPLETED').length}
              </span>
              <span className="text-[11px] text-emerald-600 font-semibold">Sorunsuz Tamamlandı</span>
            </div>
          </div>
        </div>

        {/* View Switcher & Category Filter */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-2">
          {/* Main Views */}
          <div className="flex items-center gap-1 bg-slate-100 dark:bg-[#0b101d] p-1 rounded-xl border border-slate-200 dark:border-slate-800">
            <button
              onClick={() => setActiveView('calendar')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${
                activeView === 'calendar'
                  ? 'bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 shadow-sm border border-slate-200 dark:border-slate-700'
                  : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
              }`}
            >
              <CalendarIcon className="w-3.5 h-3.5 text-sky-500" />
              <span>Dinamik Takvim Görünümü</span>
            </button>

            <button
              onClick={() => setActiveView('timeline')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${
                activeView === 'timeline'
                  ? 'bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 shadow-sm border border-slate-200 dark:border-slate-700'
                  : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
              }`}
            >
              <Milestone className="w-3.5 h-3.5 text-amber-500" />
              <span>Kronolojik Çizelge (Timeline)</span>
            </button>

            <button
              onClick={() => setActiveView('urgent_table')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${
                activeView === 'urgent_table'
                  ? 'bg-white dark:bg-slate-800 text-slate-900 dark:text-slate-100 shadow-sm border border-slate-200 dark:border-slate-700'
                  : 'text-slate-500 hover:text-slate-800 dark:hover:text-slate-200'
              }`}
            >
              <AlertTriangle className="w-3.5 h-3.5 text-rose-500" />
              <span>Acil Süreler Masası</span>
            </button>
          </div>

          {/* Category Filter Chips */}
          <div className="flex items-center gap-1 overflow-x-auto text-xs pb-1 sm:pb-0">
            <span className="text-slate-400 font-medium text-[11px] mr-1 hidden sm:inline">Kategori:</span>
            {[
              { id: 'ALL', label: 'Tümü' },
              { id: 'DEADLINE', label: 'Kesin Süreler' },
              { id: 'HEARING', label: 'Duruşmalar' },
              { id: 'STATUTE', label: 'Zamanaşımı' }
            ].map((f) => (
              <button
                key={f.id}
                onClick={() => setCategoryFilter(f.id as any)}
                className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition shrink-0 ${
                  categoryFilter === f.id
                    ? 'bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900'
                    : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200'
                }`}
              >
                {f.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* ========================================================= */}
      {/* 1. VIEW: DYNAMIC INTERACTIVE CALENDAR                     */}
      {/* ========================================================= */}
      {activeView === 'calendar' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Calendar Grid (8 cols) */}
          <div className="lg:col-span-8 bg-white dark:bg-[#131d31] border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm space-y-4">
            {/* Calendar Header Navigation */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <h3 className="text-base font-extrabold text-slate-900 dark:text-slate-100">
                  {monthNames[month]} {year}
                </h3>
                <span className="text-[11px] text-slate-400 font-medium">
                  {events.filter((e) => e.date.startsWith(`${year}-${(month + 1).toString().padStart(2, '0')}`)).length} Adli Olay
                </span>
              </div>

              <div className="flex items-center gap-1.5">
                <button
                  onClick={jumpToToday}
                  className="px-2.5 py-1 text-xs font-bold rounded-lg bg-sky-50 dark:bg-sky-950/40 text-sky-700 dark:text-sky-300 border border-sky-200 dark:border-sky-800 hover:bg-sky-100"
                >
                  Bugün
                </button>
                <button
                  onClick={prevMonth}
                  className="p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800"
                  title="Önceki Ay"
                >
                  <ChevronLeft className="w-4 h-4" />
                </button>
                <button
                  onClick={nextMonth}
                  className="p-1.5 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800"
                  title="Sonraki Ay"
                >
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Weekday Names Header */}
            <div className="grid grid-cols-7 gap-1 text-center text-[11px] font-bold text-slate-400 uppercase tracking-wider py-1 border-b border-slate-100 dark:border-slate-800">
              <span>Pzt</span>
              <span>Sal</span>
              <span>Çar</span>
              <span>Per</span>
              <span>Cum</span>
              <span className="text-rose-400">Cmt</span>
              <span className="text-rose-400">Paz</span>
            </div>

            {/* Calendar Days Matrix */}
            <div className="grid grid-cols-7 gap-1.5">
              {/* Empty leading cells */}
              {Array.from({ length: firstDayIndex }).map((_, idx) => (
                <div key={`empty-${idx}`} className="h-24 p-1 rounded-xl bg-slate-50/40 dark:bg-slate-900/20 opacity-30" />
              ))}

              {/* Month Days */}
              {Array.from({ length: totalDays }).map((_, idx) => {
                const dayNum = idx + 1;
                const formattedDateStr = `${year}-${(month + 1).toString().padStart(2, '0')}-${dayNum
                  .toString()
                  .padStart(2, '0')}`;
                const isToday = formattedDateStr === '2026-09-24';
                const isSelected = formattedDateStr === selectedDateStr;

                const dayEvents = events.filter((e) => e.date === formattedDateStr);
                const hasDeadline = dayEvents.some((e) => e.category === 'DEADLINE');
                const hasHearing = dayEvents.some((e) => e.category === 'HEARING');
                const hasStatute = dayEvents.some((e) => e.category === 'STATUTE');

                return (
                  <div
                    key={`day-${dayNum}`}
                    onClick={() => setSelectedDateStr(formattedDateStr)}
                    className={`h-24 p-1.5 rounded-xl border text-left transition cursor-pointer flex flex-col justify-between ${
                      isSelected
                        ? 'border-sky-500 bg-sky-50/50 dark:bg-sky-950/30 ring-2 ring-sky-500/20 shadow-xs'
                        : isToday
                        ? 'border-amber-500 bg-amber-50/30 dark:bg-amber-950/20'
                        : 'border-slate-100 dark:border-slate-800/80 hover:border-slate-300 dark:hover:border-slate-700 bg-white dark:bg-[#0e1626]'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span
                        className={`text-xs font-bold w-5 h-5 flex items-center justify-center rounded-full ${
                          isToday
                            ? 'bg-amber-500 text-white font-extrabold'
                            : isSelected
                            ? 'bg-sky-600 text-white'
                            : 'text-slate-800 dark:text-slate-200'
                        }`}
                      >
                        {dayNum}
                      </span>

                      {/* Urgency Dot Flags */}
                      <div className="flex items-center gap-1">
                        {hasDeadline && <span className="w-2 h-2 rounded-full bg-rose-500 animate-pulse" title="Kesin Süre" />}
                        {hasHearing && <span className="w-2 h-2 rounded-full bg-sky-500" title="Duruşma" />}
                        {hasStatute && <span className="w-2 h-2 rounded-full bg-purple-500" title="Zamanaşımı" />}
                      </div>
                    </div>

                    {/* Mini event tags inside cell */}
                    <div className="space-y-1 overflow-hidden">
                      {dayEvents.slice(0, 2).map((ev) => (
                        <div
                          key={ev.id}
                          className={`text-[9px] px-1 py-0.5 rounded truncate font-semibold ${
                            ev.category === 'DEADLINE'
                              ? 'bg-rose-100 dark:bg-rose-950/50 text-rose-700 dark:text-rose-300'
                              : ev.category === 'HEARING'
                              ? 'bg-sky-100 dark:bg-sky-950/50 text-sky-700 dark:text-sky-300'
                              : 'bg-purple-100 dark:bg-purple-950/50 text-purple-700 dark:text-purple-300'
                          }`}
                          title={`${ev.title} (${ev.time || ''})`}
                        >
                          {ev.time ? `${ev.time} ` : ''}{ev.title}
                        </div>
                      ))}
                      {dayEvents.length > 2 && (
                        <span className="text-[9px] text-slate-400 font-bold block pl-0.5">
                          +{dayEvents.length - 2} olay daha
                        </span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Selected Date Details Sidebar (4 cols) */}
          <div className="lg:col-span-4 bg-white dark:bg-[#131d31] border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm space-y-4 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
                    Seçili Günün Programı
                  </span>
                  <h4 className="text-sm font-extrabold text-slate-900 dark:text-slate-100 mt-0.5">
                    {selectedDateStr}
                  </h4>
                </div>
                <span className="text-xs font-bold px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300">
                  {selectedDateEvents.length} Adli Kayıt
                </span>
              </div>

              {selectedDateEvents.length === 0 ? (
                <div className="text-center py-10 px-4 bg-slate-50 dark:bg-[#0b101d] rounded-xl border border-dashed border-slate-200 dark:border-slate-800 text-xs text-slate-500 space-y-2">
                  <CalendarIcon className="w-8 h-8 text-slate-400 mx-auto" />
                  <p className="font-semibold text-slate-700 dark:text-slate-300">Bu tarihte kayıtlı bir süre veya duruşma yok.</p>
                  <p className="text-[11px]">
                    Yukarıdaki "Yeni Süre / Duruşma Ekle" butonuna basarak bu güne bildirim ekleyebilirsiniz.
                  </p>
                </div>
              ) : (
                <div className="space-y-3">
                  {selectedDateEvents.map((evt) => {
                    const badge = getCategoryBadge(evt.category);
                    return (
                      <div
                        key={evt.id}
                        className={`p-3.5 rounded-xl border space-y-2 relative transition ${
                          evt.status === 'COMPLETED'
                            ? 'bg-slate-50 dark:bg-slate-900/40 border-slate-200 dark:border-slate-800 opacity-75'
                            : evt.category === 'DEADLINE'
                            ? 'bg-rose-50/40 dark:bg-rose-950/20 border-rose-200 dark:border-rose-900/50'
                            : evt.category === 'HEARING'
                            ? 'bg-sky-50/40 dark:bg-sky-950/20 border-sky-200 dark:border-sky-900/50'
                            : 'bg-purple-50/40 dark:bg-purple-950/20 border-purple-200 dark:border-purple-900/50'
                        }`}
                      >
                        <div className="flex items-start justify-between gap-2">
                          <div className="flex items-center gap-1.5 flex-wrap">
                            <span className={`text-[10px] font-bold px-2 py-0.5 rounded-md border ${badge.color}`}>
                              {badge.label}
                            </span>
                            {evt.time && (
                              <span className="text-[11px] font-mono font-bold text-slate-700 dark:text-slate-300 flex items-center gap-1">
                                <Clock className="w-3 h-3 text-slate-400" />
                                {evt.time}
                              </span>
                            )}
                          </div>

                          <div className="flex items-center gap-1">
                            <button
                              onClick={() => handleToggleCompleted(evt.id)}
                              className={`p-1 rounded transition ${
                                evt.status === 'COMPLETED'
                                  ? 'text-emerald-500 hover:text-slate-400'
                                  : 'text-slate-400 hover:text-emerald-500'
                              }`}
                              title={evt.status === 'COMPLETED' ? 'Tamamlanmadı yap' : 'Tamamlandı olarak işaretle'}
                            >
                              <CheckCircle2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDeleteEvent(evt.id)}
                              className="p-1 text-slate-400 hover:text-rose-500 transition"
                              title="Sil"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </div>

                        <h5 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                          {evt.title}
                        </h5>

                        {evt.lawReference && (
                          <div className="text-[11px] font-medium text-slate-600 dark:text-slate-300">
                            <strong>Mevzuat:</strong> {evt.lawReference}
                          </div>
                        )}

                        {evt.consequence && (
                          <div className="text-[11px] text-rose-700 dark:text-rose-300 bg-rose-100/50 dark:bg-rose-950/40 p-2 rounded-lg border border-rose-200 dark:border-rose-900/50">
                            <strong>Risk / Hukuki Sonuç:</strong> {evt.consequence}
                          </div>
                        )}

                        {evt.notes && (
                          <p className="text-[11px] text-slate-500 dark:text-slate-400 italic">
                            "{evt.notes}"
                          </p>
                        )}

                        {/* Calendar Sync Links */}
                        <div className="pt-2 border-t border-slate-200/60 dark:border-slate-800 flex items-center justify-between text-xs">
                          {getUrgencyBadge(evt.date, evt.status)}

                          <div className="flex items-center gap-1.5">
                            <a
                              href={generateGoogleCalendarUrl(evt)}
                              target="_blank"
                              rel="noreferrer"
                              className="p-1 px-2 text-[10px] font-semibold rounded bg-sky-50 dark:bg-sky-950/40 text-sky-700 dark:text-sky-300 border border-sky-200 dark:border-sky-800 hover:bg-sky-100 transition flex items-center gap-1"
                              title="Google Calendar'a Ekle"
                            >
                              <ExternalLink className="w-3 h-3" />
                              <span>Google Takvim</span>
                            </a>
                            <button
                              onClick={() => downloadIcsFile(evt)}
                              className="p-1 px-2 text-[10px] font-semibold rounded bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-200 transition"
                              title="Tekil .ics İndir"
                            >
                              .ics
                            </button>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Quick HMK Note Helper */}
            <div className="bg-amber-50/70 dark:bg-amber-950/30 p-3 rounded-xl border border-amber-200/80 dark:border-amber-900/40 text-[11px] text-amber-900 dark:text-amber-200 space-y-1">
              <span className="font-bold flex items-center gap-1">
                <Info className="w-3.5 h-3.5 text-amber-600" /> HMK Usul İpucu:
              </span>
              <p>
                Süreler taraflara tebliğle başlar. Son gün resmi tatile rastlarsa tatili takip eden ilk iş günü mesai
                bitiminde sona erer (HMK m. 93).
              </p>
            </div>
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* 2. VIEW: CHRONOLOGICAL TIMELINE (GANTT / MILESTONE VIEW) */}
      {/* ========================================================= */}
      {activeView === 'timeline' && (
        <div className="bg-white dark:bg-[#131d31] border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm space-y-6">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100">
                Kronolojik Dava Yaşam Döngüsü & Kritik Eşikler
              </h3>
              <p className="text-xs text-slate-500">
                Davanın açılışından kesin hüküm anına kadar olan tüm usul adımları ve kesin süreler.
              </p>
            </div>
            <span className="text-xs font-semibold px-2.5 py-1 rounded-lg bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">
              Toplam {filteredEvents.length} Aşama
            </span>
          </div>

          {/* Timeline Nodes */}
          <div className="relative pl-6 space-y-8 before:absolute before:left-3 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-200 dark:before:bg-slate-800">
            {filteredEvents.map((evt) => {
              const badge = getCategoryBadge(evt.category);
              const daysRemaining = getDaysRemaining(evt.date);
              const isUrgent = daysRemaining <= 4 && daysRemaining >= 0 && evt.status !== 'COMPLETED';

              return (
                <div key={evt.id} className="relative group">
                  {/* Timeline Node Icon Circle */}
                  <div
                    className={`absolute -left-[1.85rem] top-1 w-6 h-6 rounded-full border-2 flex items-center justify-center transition ${
                      evt.status === 'COMPLETED'
                        ? 'bg-emerald-500 border-white dark:border-slate-900 text-white'
                        : isUrgent
                        ? 'bg-rose-500 border-rose-200 text-white animate-pulse'
                        : evt.category === 'HEARING'
                        ? 'bg-sky-500 border-sky-200 text-white'
                        : 'bg-slate-100 dark:bg-slate-800 border-slate-300 dark:border-slate-700 text-slate-600 dark:text-slate-300'
                    }`}
                  >
                    {evt.status === 'COMPLETED' ? (
                      <Check className="w-3.5 h-3.5" />
                    ) : evt.category === 'HEARING' ? (
                      <Gavel className="w-3 h-3" />
                    ) : isUrgent ? (
                      <AlertTriangle className="w-3 h-3" />
                    ) : (
                      <Clock className="w-3 h-3" />
                    )}
                  </div>

                  {/* Card Content */}
                  <div
                    className={`p-4 rounded-2xl border transition shadow-xs space-y-2.5 ${
                      evt.status === 'COMPLETED'
                        ? 'bg-slate-50/60 dark:bg-slate-900/30 border-slate-200 dark:border-slate-800 opacity-80'
                        : isUrgent
                        ? 'bg-rose-50/50 dark:bg-rose-950/20 border-rose-300 dark:border-rose-900/60 ring-1 ring-rose-500/20'
                        : 'bg-white dark:bg-[#0e1626] border-slate-200 dark:border-slate-800 hover:border-slate-300'
                    }`}
                  >
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-md border ${badge.color}`}>
                          {badge.label}
                        </span>
                        <span className="text-xs font-extrabold text-slate-800 dark:text-slate-200">
                          {evt.date} {evt.time ? `• ${evt.time}` : ''}
                        </span>
                        {evt.lawReference && (
                          <span className="text-[11px] font-semibold text-slate-600 dark:text-slate-400 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded border border-slate-200 dark:border-slate-700">
                            {evt.lawReference}
                          </span>
                        )}
                      </div>

                      <div className="flex items-center gap-2">
                        {getUrgencyBadge(evt.date, evt.status)}
                        <button
                          onClick={() => handleToggleCompleted(evt.id)}
                          className={`p-1 rounded text-xs transition ${
                            evt.status === 'COMPLETED' ? 'text-emerald-500' : 'text-slate-400 hover:text-emerald-500'
                          }`}
                        >
                          <CheckCircle2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    <h4 className="text-sm font-bold text-slate-900 dark:text-slate-100">
                      {evt.title}
                    </h4>

                    {evt.consequence && (
                      <div className="text-xs text-rose-800 dark:text-rose-300 bg-rose-100/60 dark:bg-rose-950/40 p-2.5 rounded-xl border border-rose-200 dark:border-rose-900/40">
                        <strong className="block text-[10px] uppercase font-bold text-rose-600 dark:text-rose-400">
                          Hukuki Yaptırım & Risk:
                        </strong>
                        {evt.consequence}
                      </div>
                    )}

                    {evt.notes && (
                      <p className="text-xs text-slate-600 dark:text-slate-300 font-serif">
                        "{evt.notes}"
                      </p>
                    )}

                    {/* Bottom Actions */}
                    <div className="flex items-center justify-between pt-2 border-t border-slate-100 dark:border-slate-800 text-xs">
                      <span className="text-[11px] text-slate-400">
                        {evt.court} — {evt.caseNo}
                      </span>

                      <div className="flex items-center gap-1.5">
                        <a
                          href={generateGoogleCalendarUrl(evt)}
                          target="_blank"
                          rel="noreferrer"
                          className="flex items-center gap-1 px-2.5 py-1 text-[11px] font-bold rounded-lg bg-sky-50 dark:bg-sky-950/40 text-sky-700 dark:text-sky-300 border border-sky-200 dark:border-sky-800 hover:bg-sky-100 transition"
                        >
                          <ExternalLink className="w-3 h-3" />
                          <span>Google Takvim</span>
                        </a>

                        <button
                          onClick={() => downloadIcsFile(evt)}
                          className="px-2 py-1 text-[11px] font-semibold rounded-lg bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 hover:bg-slate-200 transition"
                        >
                          .ics İndir
                        </button>

                        <button
                          onClick={() => handleDeleteEvent(evt.id)}
                          className="p-1 text-slate-400 hover:text-rose-500 transition"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* 3. VIEW: URGENT DEADLINES TABLE                           */}
      {/* ========================================================= */}
      {activeView === 'urgent_table' && (
        <div className="bg-white dark:bg-[#131d31] border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
            <div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-rose-500" />
                Acil Kesin Süreler ve Hak Düşürücü Süre Takip Masası
              </h3>
              <p className="text-xs text-slate-500">
                Kaçırılması halinde telafisi imkansız hak kaybına yol açabilecek kesin ve süreli işlemler.
              </p>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-50 dark:bg-[#0b101d] text-slate-400 text-[10px] uppercase font-bold tracking-wider border-b border-slate-200 dark:border-slate-800">
                <tr>
                  <th className="p-3">Süre Başlığı & Dava</th>
                  <th className="p-3">Kategori</th>
                  <th className="p-3">Son Gün (Tarih & Saat)</th>
                  <th className="p-3">Kalan Süre</th>
                  <th className="p-3">Yasal Dayanak & Risk</th>
                  <th className="p-3 text-right">Eylemler</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800/80">
                {events.map((evt) => {
                  const badge = getCategoryBadge(evt.category);
                  const days = getDaysRemaining(evt.date);
                  return (
                    <tr
                      key={evt.id}
                      className={`hover:bg-slate-50/50 dark:hover:bg-slate-800/40 transition ${
                        days <= 4 && days >= 0 && evt.status !== 'COMPLETED'
                          ? 'bg-rose-50/30 dark:bg-rose-950/10'
                          : ''
                      }`}
                    >
                      <td className="p-3">
                        <span className="font-bold text-slate-900 dark:text-slate-100 block">
                          {evt.title}
                        </span>
                        <span className="text-[10px] text-slate-400">
                          {evt.court} • {evt.caseNo}
                        </span>
                      </td>
                      <td className="p-3">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${badge.color}`}>
                          {badge.label}
                        </span>
                      </td>
                      <td className="p-3 font-mono font-bold text-slate-800 dark:text-slate-200">
                        {evt.date} {evt.time ? `• ${evt.time}` : ''}
                      </td>
                      <td className="p-3">{getUrgencyBadge(evt.date, evt.status)}</td>
                      <td className="p-3 max-w-xs">
                        <span className="text-[11px] font-semibold text-slate-700 dark:text-slate-300 block">
                          {evt.lawReference}
                        </span>
                        <span className="text-[10px] text-rose-600 dark:text-rose-400 line-clamp-1">
                          {evt.consequence}
                        </span>
                      </td>
                      <td className="p-3 text-right">
                        <div className="flex items-center justify-end gap-1.5">
                          <a
                            href={generateGoogleCalendarUrl(evt)}
                            target="_blank"
                            rel="noreferrer"
                            className="p-1 px-2 text-[10px] font-bold rounded bg-sky-50 dark:bg-sky-950/40 text-sky-700 dark:text-sky-300 border border-sky-200 dark:border-sky-800 hover:bg-sky-100"
                            title="Google Takvime Ekle"
                          >
                            Takvim
                          </a>
                          <button
                            onClick={() => handleToggleCompleted(evt.id)}
                            className="p-1 text-slate-400 hover:text-emerald-500"
                          >
                            <CheckCircle2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ========================================================= */}
      {/* MODAL: ADD NEW DEADLINE / HEARING & PROCEDURAL CALCULATOR */}
      {/* ========================================================= */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white dark:bg-[#131d31] border border-slate-200 dark:border-slate-800 rounded-2xl max-w-xl w-full p-6 space-y-4 shadow-xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-3">
              <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <Plus className="w-4 h-4 text-sky-500" /> Yeni Dava Süresi / Duruşma Ekle
              </h3>
              <button
                onClick={() => setShowAddModal(false)}
                className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 text-sm font-bold"
              >
                ✕
              </button>
            </div>

            {/* Quick Procedural Calculation Preset Helper */}
            <div className="p-3 bg-sky-50/60 dark:bg-[#0e1626] border border-sky-200 dark:border-sky-900/40 rounded-xl space-y-2 text-xs">
              <span className="font-bold text-sky-900 dark:text-sky-300 block flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-sky-500" />
                HMK Adli Süre Otomatik Hesaplayıcı (Tebliğ + Yasal Süre):
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <div>
                  <label className="text-[10px] font-semibold text-slate-500 block mb-0.5">Tebliğ Tarihi:</label>
                  <input
                    type="date"
                    value={calcNoticeDate}
                    onChange={(e) => setCalcNoticeDate(e.target.value)}
                    className="w-full p-1.5 text-xs bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg text-slate-800 dark:text-slate-100"
                  />
                </div>
                <div>
                  <label className="text-[10px] font-semibold text-slate-500 block mb-0.5">Yasal Süre Kuralı:</label>
                  <select
                    value={calcRuleType}
                    onChange={(e) => setCalcRuleType(e.target.value)}
                    className="w-full p-1.5 text-xs bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 rounded-lg text-slate-800 dark:text-slate-100"
                  >
                    <option value="hmk_281">Bilirkişi Raporuna İtiraz (2 Hafta - HMK 281)</option>
                    <option value="hmk_122">Davaya Cevap Dilekçesi (2 Hafta - HMK 122)</option>
                    <option value="hmk_345">İstinaf Başvurusu (2 Hafta - HMK 345)</option>
                    <option value="hmk_394">İhtiyati Tedbire İtiraz (1 Hafta - HMK 394)</option>
                    <option value="tbk_72_2">Haksız Fiil Tazminatı (2 Yıl - TBK 72)</option>
                    <option value="tbk_146">Genel Zamanaşımı (10 Yıl - TBK 146)</option>
                  </select>
                </div>
              </div>
              <button
                type="button"
                onClick={handleApplyProceduralCalculation}
                className="w-full py-1 text-[11px] font-bold bg-sky-600 hover:bg-sky-500 text-white rounded-lg transition"
              >
                Tarihi & Bilgileri Hesaplayıp Forma Doldur
              </button>
            </div>

            {/* Main Form Fields */}
            <div className="space-y-3 text-xs">
              <div>
                <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Başlık</label>
                <input
                  type="text"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="örn: Bilirkişi Ek Raporuna İtiraz Süresi..."
                  className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100 focus:outline-none focus:border-sky-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Kategori</label>
                  <select
                    value={newCategory}
                    onChange={(e) => setNewCategory(e.target.value as any)}
                    className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100"
                  >
                    <option value="DEADLINE">Kesin / Hak Düşürücü Süre</option>
                    <option value="HEARING">Duruşma / Celse</option>
                    <option value="STATUTE">Zamanaşımı Dolumu</option>
                    <option value="PROCEDURAL">Usul & Arabuluculuk</option>
                  </select>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Tarih</label>
                    <input
                      type="date"
                      value={newDate}
                      onChange={(e) => setNewDate(e.target.value)}
                      className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100"
                    />
                  </div>
                  <div>
                    <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Saat</label>
                    <input
                      type="time"
                      value={newTime}
                      onChange={(e) => setNewTime(e.target.value)}
                      className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100"
                    />
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">
                    Yasal Dayanak / Madde
                  </label>
                  <input
                    type="text"
                    value={newLawRef}
                    onChange={(e) => setNewLawRef(e.target.value)}
                    placeholder="örn: HMK m. 281"
                    className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100"
                  />
                </div>
                <div>
                  <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">
                    Mahkeme & Dosya No
                  </label>
                  <input
                    type="text"
                    value={newCourt}
                    onChange={(e) => setNewCourt(e.target.value)}
                    placeholder="örn: İstanbul 14. ATM - 2026/412 E."
                    className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100"
                  />
                </div>
              </div>

              <div>
                <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">
                  Kaçırılırsa Doğacak Hukuki Sonuç (Risk)
                </label>
                <input
                  type="text"
                  value={newConsequence}
                  onChange={(e) => setNewConsequence(e.target.value)}
                  placeholder="örn: Bilirkişi raporu aleyhe kesinleşir; itiraz hakkı düşer."
                  className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100"
                />
              </div>

              <div>
                <label className="font-semibold text-slate-700 dark:text-slate-300 block mb-1">Avukat Notları</label>
                <textarea
                  rows={2}
                  value={newNotes}
                  onChange={(e) => setNewNotes(e.target.value)}
                  placeholder="Dosyaya özel detaylar ve hatırlatmalar..."
                  className="w-full p-2 bg-slate-50 dark:bg-[#0b101d] border border-slate-300 dark:border-slate-700 rounded-xl text-slate-800 dark:text-slate-100"
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100 dark:border-slate-800">
              <button
                type="button"
                onClick={() => setShowAddModal(false)}
                className="px-4 py-2 text-xs font-semibold text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
              >
                İptal
              </button>
              <button
                type="button"
                onClick={handleAddEvent}
                className="px-5 py-2 text-xs font-bold bg-sky-600 hover:bg-sky-500 text-white rounded-xl shadow-sm transition"
              >
                Takvime Kaydet
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
